server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${quick.datasource.driver-class-name}
      url: jdbc:mysql://${quick.datasource.host}:${quick.datasource.port}/${quick.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${quick.datasource.username}
      password: ${quick.datasource.password}
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quick.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      quick:
        mapper: debug
        service: info
        controller: info

quick:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ueme
    # 设置jwt过期时间  以下为毫秒  转换为 10小时
    admin-ttl: 36000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  minio:
    endpoint: http://10.10.1.198:9000
    accessKey: admin
    secretKey: admin123456
    bucketName: quick-itcast
